.PHONY: test test-cover test-internal format build clean
PKG=github.com/wadmit/eradicate
TEST_DIR=./tests
TEST_INTERNAL = ./internal/...
VERSION := `git fetch --tags && git tag | sort -V | tail -1`
LDFLAGS=-ldflags "-X=github.com/wadmit/eradicate/v0/cmd.Version=$(VERSION)"
COVER=--cover --coverprofile=cover.out

format:
	go fmt ./...
test-cover: 
	go test -v $(TEST_DIR)/... --race $(COVER) $(PKG)
	go tool cover -html=cover.out

test-internal: format
	go test -v $(TEST_INTERNAL) --race $(PKG) 

test: format
	go test -v $(TEST_DIR)/... --race $(PKG) 

build: format
	go mod tidy
	go build $(LDFLAGS)

clean:
	find . -type f -name '*.got.*' -delete
	find . -type f -name '*.out' -delete
