name: "Commit Message Check"
on:
  pull_request:
    branches:
      - "*"

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:  
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: "^.{0,50}$"
          error: "The maximum line length of 50 characters is exceeded."

      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(fix|feat|docs): .+, issue #\d+$'
          flags: "gm"
          error: 'Your commit message must be in the format "fix: message_here, issue: #<issue_number>"'

