name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and package
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh $VERSION

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz,build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}