name: Build and Release

on:
  push:
    # branches:
    #   - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Build and package
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
